# Generated by Django 5.2.8 on 2025-11-16 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailyMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="Дата")),
                (
                    "total_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Общая выручка",
                    ),
                ),
                (
                    "total_orders",
                    models.IntegerField(default=0, verbose_name="Всего заказов"),
                ),
                (
                    "avg_order_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Средний чек",
                    ),
                ),
                (
                    "products_sold",
                    models.IntegerField(default=0, verbose_name="Товаров продано"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлен"),
                ),
            ],
            options={
                "verbose_name": "Ежедневные метрики",
                "verbose_name_plural": "Ежедневные метрики",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="DataSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название источника"),
                ),
                (
                    "api_endpoint",
                    models.URLField(blank=True, verbose_name="API endpoint"),
                ),
                (
                    "api_key",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="API ключ"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "last_sync",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Последняя синхронизация"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
            ],
            options={
                "verbose_name": "Источник данных",
                "verbose_name_plural": "Источники данных",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sku",
                    models.CharField(max_length=100, unique=True, verbose_name="SKU"),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название товара"),
                ),
                (
                    "category",
                    models.CharField(max_length=100, verbose_name="Категория"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлен"),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
                "indexes": [
                    models.Index(fields=["sku"], name="etl_pipelin_sku_0cb317_idx"),
                    models.Index(
                        fields=["category"], name="etl_pipelin_categor_d085f1_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SalesData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата продажи")),
                ("quantity", models.IntegerField(verbose_name="Количество")),
                (
                    "revenue",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Выручка"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="etl_pipeline.product",
                        verbose_name="Товар",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="etl_pipeline.datasource",
                        verbose_name="Источник",
                    ),
                ),
            ],
            options={
                "verbose_name": "Данные о продажах",
                "verbose_name_plural": "Данные о продажах",
                "indexes": [
                    models.Index(fields=["date"], name="etl_pipelin_date_db2e0e_idx"),
                    models.Index(
                        fields=["product"], name="etl_pipelin_product_a6f169_idx"
                    ),
                    models.Index(
                        fields=["source"], name="etl_pipelin_source__972615_idx"
                    ),
                ],
                "unique_together": {("product", "date", "source")},
            },
        ),
    ]
